AllCops:
  TargetRubyVersion: 2.4
  Include:
    - '**/Rakefile'
    - '**/config.ru'
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/*'
    - 'client/**/*'

Metrics/LineLength:
  Enabled: false

Style/FileName:
  Exclude:
    - 'Gemfile'

Documentation:
  Enabled: false

ClassAndModuleChildren:
  Enabled: false
